# Generated by Django 4.1.5 on 2023-03-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
        ('home', '0006_group_group_members_alter_group_group_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_members',
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_position', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appuser')),
            ],
            options={
                'unique_together': {('user_id', 'group_id')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(related_name='group_users', through='home.GroupUsers', to='user.appuser'),
        ),
    ]
