# Generated by Django 4.1.5 on 2023-03-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_group_group_members_alter_group_group_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_members',
        ),
    ]
