# Generated by Django 4.1.5 on 2023-03-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
        ('home', '0007_remove_group_group_members_groupusers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_position', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_users',
        ),
        migrations.DeleteModel(
            name='GroupUsers',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appuser'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(related_name='group_members', through='home.GroupMembers', to='user.appuser'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together={('user_id', 'group_id')},
        ),
    ]
