# Generated by Django 4.1.5 on 2023-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_groupmembers_group_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_players',
            field=models.IntegerField(default=8),
        ),
    ]
