# Generated by Django 4.1.5 on 2023-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_groupmembers_group_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='final_position',
        ),
        migrations.AddField(
            model_name='group',
            name='max_players',
            field=models.IntegerField(default=8),
        ),
    ]
