# Generated by Django 4.1.5 on 2023-03-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_group_max_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='final_position',
        ),
    ]
