# Generated by Django 4.1.5 on 2023-02-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_appuser_item_purchased_by_delete_purchases'),
        ('game', '0004_completion_playing_alter_completions_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='keeper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appuser'),
        ),
        migrations.DeleteModel(
            name='Completions',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.AddField(
            model_name='playing',
            name='active_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.task'),
        ),
        migrations.AddField(
            model_name='playing',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='playing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appuser'),
        ),
        migrations.AddField(
            model_name='completion',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.task'),
        ),
        migrations.AddField(
            model_name='completion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appuser'),
        ),
        migrations.AddField(
            model_name='game',
            name='users_playing',
            field=models.ManyToManyField(related_name='users_playing', through='game.Playing', to='user.appuser'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(related_name='completions', through='game.Completion', to='user.appuser'),
        ),
        migrations.AlterUniqueTogether(
            name='playing',
            unique_together={('user_id', 'game_id')},
        ),
        migrations.AlterUniqueTogether(
            name='completion',
            unique_together={('user_id', 'task_id')},
        ),
    ]
