# Generated by Django 4.1.5 on 2023-02-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_keeper_id_delete_completions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Task', max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.IntegerField(choices=[(0, 'waitingForPlayers'), (1, 'settingTask'), (2, 'respondToTask'), (3, 'waitingForRanking'), (4, 'displayCurrentResults'), (5, 'endOfGame')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('T', 'Default'), ('L', 'Location')], max_length=1),
        ),
    ]
