# Generated by Django 4.1.5 on 2023-02-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_task_task_description_task_task_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_code',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
