# Generated by Django 4.1.5 on 2023-02-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_game_code_game_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_datetime',
        ),
    ]
