# Generated by Django 4.1.5 on 2023-03-01 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_game_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playing',
            name='active_task',
        ),
        migrations.AddField(
            model_name='game',
            name='active_task_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='game',
            name='max_rounds',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='Game', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
