# Generated by Django 4.1.5 on 2023-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_playing_points_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion',
            name='submission_uri',
        ),
        migrations.RemoveField(
            model_name='game',
            name='keeper_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='users_playing',
        ),
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='completion',
            name='submission',
            field=models.BinaryField(null=True),
        ),
        migrations.DeleteModel(
            name='Playing',
        ),
    ]
