# Generated by Django 4.1.5 on 2023-03-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_completion_submission_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='max_players',
        ),
    ]
