# Generated by Django 4.1.5 on 2023-03-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
        ('game', '0012_remove_completion_submission_uri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.BinaryField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_by',
        ),
        migrations.DeleteModel(
            name='Completion',
        ),
        migrations.AddField(
            model_name='submission',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appuser'),
        ),
        migrations.AddField(
            model_name='game',
            name='submissions',
            field=models.ManyToManyField(related_name='game_submissions', through='game.Submission', to='user.appuser'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user_id', 'game_id')},
        ),
    ]
