# Generated by Django 4.1.5 on 2023-03-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
        ('game', '0013_remove_game_max_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_position', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appuser')),
            ],
            options={
                'unique_together': {('user_id', 'game_id')},
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_by',
        ),
        migrations.DeleteModel(
            name='Completion',
        ),
        migrations.AddField(
            model_name='game',
            name='users_playing',
            field=models.ManyToManyField(related_name='users_playing', through='game.Playing', to='user.appuser'),
        ),
    ]
