# Generated by Django 4.1.5 on 2023-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_submission_remove_game_max_players_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='active_task_number',
            new_name='current_round_number',
        ),
        migrations.AddField(
            model_name='game',
            name='current_round_name',
            field=models.CharField(default='Task', max_length=64),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
