# Generated by Django 4.1.5 on 2023-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_active_task_number_game_current_round_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
