# Generated by Django 4.1.5 on 2023-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_playing_remove_task_completed_by_delete_completion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playing',
            name='final_position',
        ),
        migrations.RemoveField(
            model_name='playing',
            name='points_earned',
        ),
        migrations.AddField(
            model_name='playing',
            name='submission',
            field=models.BinaryField(null=True),
        ),
    ]
