# Generated by Django 4.1.5 on 2023-03-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
        ('game', '0015_remove_playing_final_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playing',
            new_name='Completion',
        ),
    ]
