# Generated by Django 4.1.5 on 2023-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
        ('game', '0016_rename_playing_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='users_playing',
            field=models.ManyToManyField(related_name='game_submissions', through='game.Completion', to='user.appuser'),
        ),
    ]
