# Generated by Django 4.1.5 on 2023-03-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_game_users_playing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='users_playing',
            new_name='submissions',
        ),
    ]
