# Generated by Django 4.1.5 on 2023-03-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
        ('game', '0018_rename_users_playing_game_submissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Completion',
            new_name='Submission',
        ),
    ]
