name: Django Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run database migrations
      run: python /home/runner/work/ECM2434-Group-Software-Development-Project-Group-27/ECM2434-Group-Software-Development-Project-Group-27/mysite/manage.py migrate
    - name: Run tests
      run: |
        echo "Running tests..."
        python /home/runner/work/ECM2434-Group-Software-Development-Project-Group-27/ECM2434-Group-Software-Development-Project-Group-27/mysite/manage.py test



